### ISSUE TITLE
Unable to recognize instance_material from DAE

### ISSUE THREAD

**Issue by RubeAka** [andresoviedo/android-3D-model-viewer#105]
Hi,
I tried to load a DAE model but the texture wasn't loaded.
I found that GeometryLoader was trying to find materials from library_material but there is no match.
Those materials it was trying to find is resided in instance_material which would redirect it back to library_material and with additional information.
I don't have any knowledge about DAE's format, so this is quite hard for me to solve it or even workaround it.

Model's path:
http://www.cadnav.com/3d-models/model-42981.html

**Comment by andresoviedo** [comment]
Fixed in latest version. Please try.
Regards
