### ISSUE TITLE
Details are not clear because of the light

### ISSUE THREAD

**Issue by T0mAl3x** [andresoviedo/android-3D-model-viewer#119]
The light is a little to small and I can't see all the details on the object. How can I make a bigger light that stands still and doesn't move with the object?

Or a better aproach. How can I make the entire object to look exactly like the texture of the light?

**Comment by SmallYQ** [comment]
can i ask you a problem?i copy code in my project,but occur open dae or stl file unknow protocal :assets.when i open obj file,it is work good,but i can not textures, can you help me?

**Comment by andresoviedo** [comment]
You have already a rendering mode with "no lights" that means color is not filtered by light impact so you see either the texture or colors read from the file.
