### ISSUE TITLE
Tensorflow-Android-3D model rendering

### ISSUE THREAD

**Issue by rash1994** [andresoviedo/android-3D-model-viewer#120]
Hie,

I have made my tensorflow-android project for object detection, now where there is the detection, I wish to render a 3D model. Is that possible using this project?

Thanks and regards
Rashmi

**Comment by andresoviedo** [comment]
Hey

Yes. It is possible. This app shows you how to load and draw graphics on the screen.

However, in order to fully implement AR you would need to reconfigure app (i.e. transparent background) and setup some logic to handle the camera.
