### ISSUE TITLE
open dae or stl file unknow protocol :assets

### ISSUE THREAD

**Issue by SmallYQ** [andresoviedo/android-3D-model-viewer#123]
i copy code in my project,but occur open dae or stl file unknow protocal :assets.when i open obj file,it is work good,but i can not textures,anybody can help me?

**Comment by andresoviedo** [comment]
Hey.  Make sure you register protocol in your application.

`public class MainActivity extends Activity {

    // Custom assets handler: org/andresoviedo/util/android/assets/Handler.class
    static {
        System.setProperty("java.protocol.handler.pkgs", "org.andresoviedo.util.android");
        URL.setURLStreamHandlerFactory(new AndroidURLStreamHandlerFactory());
    }`
