### ISSUE TITLE
Import file failed

### ISSUE THREAD

**Issue by water-mu** [andresoviedo/android-3D-model-viewer#126]
Import file failed  oom

file size 120M .dae

**Comment by andresoviedo** [comment]
Hello @water-mu 
pretty big file.
can you share the model  ?
regards

**Comment by water-mu** [comment]
@andresoviedo First, change the file name, just like that ：abc.dae.001.zip -> abc.dae.zip.001
Then unzip it
[abc.dae.001.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/3850154/abc.dae.001.zip)
[abc.dae.002.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/3850156/abc.dae.002.zip)
[abc.dae.003.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/3850157/abc.dae.003.zip)

**Comment by andresoviedo** [comment]
I am setting `largeHeap=true` to the manifest
