### ISSUE TITLE
Cannot render color

### ISSUE THREAD

**Issue by Study-is-happy** [andresoviedo/android-3D-model-viewer#128]
I cannot even render texture and color when first loading the model. If I tried to turn off colors, it can render texture but still not color. It's a very nice project and appreciate for your help! :)

Here is the link:
https://drive.google.com/drive/folders/1ZTJWHPtwDSsnv-OckTZoXoLcvXQWAmPy?usp=sharing

And this model can be rendered on this site:
https://3dviewer.net/

**Comment by andresoviedo** [comment]
Fixed in latest version
Please give it a try
if you still have issues please reopen ticket
regards
