### ISSUE TITLE
Material File .mtl Proper Not Rendering?

### ISSUE THREAD

**Issue by Ram8948** [andresoviedo/android-3D-model-viewer#129]
I have Load .obj file with .mtl file. inside material file have color and texture image. after render my material color is not puted on object and texture image is draw on overall object?

**Comment by andresoviedo** [comment]
Hi.   Can you share the model files ?

**Comment by Ram8948** [comment]
this is my model file plz check it

**Comment by Ram8948** [comment]
ok i will send you model file in email

**Comment by andresoviedo** [comment]
Hello. New version of the app released.
Please give it a try
If you still have issues please reopen ticket
regards
