### ISSUE TITLE
Not compatible with Collada file generated by Cinema4D

### ISSUE THREAD

**Issue by Vanguard3000** [andresoviedo/android-3D-model-viewer#131]
Having some issues with the attached model, downloaded from [TurboSquid](https://www.turbosquid.com/FullPreview/Index.cfm/ID/1474115). The issue seems to be due to it being generated by Cinema4D as opposed to Blender.

It's worth noting that the .dae won't show in MacOS preview, and opining it in Photoshop gives some wonky results, while both methods work with another dae file we've got on hand.

[IrisMechanical.dae.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/3985452/IrisMechanical.dae.zip)

**Comment by andresoviedo** [comment]
Hello @Vanguard3000 
I'll take a look asap
Regards

**Comment by andresoviedo** [comment]
Hello.  The Iris model works for me with latest version released
Please give it a try.
If you still have issues please reopen ticket
regards
