### ISSUE TITLE
Serious Bug

### ISSUE THREAD

**Issue by zhou67832033** [andresoviedo/android-3D-model-viewer#133]
Hello, I love your code, but I find a serious bug when I use the model, please fix it, thank you!

[3DS - Pokemon X Y - 025 Pikachu.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/4251311/3DS.-.Pokemon.X.Y.-.025.Pikachu.zip)

![bug](https://user-images.githubusercontent.com/3193237/75272834-97b7b280-5839-11ea-8f25-4b4c4628f9ac.jpg)

**Comment by andresoviedo** [comment]
Hello @zhou67832033 
I will check that 
thanks for your feedback

**Comment by andresoviedo** [comment]
Fixed in latest version
Please give it a try 
Regards
