### ISSUE TITLE
Dark colors with texture

### ISSUE THREAD

**Issue by deakjahn** [andresoviedo/android-3D-model-viewer#135]
This is a classic OpenGL issue. If an object is drawn with different materials, some only colors, others with texture, the whole object will be drawn with the texture bound and using the associated shader. This results in colors becoming much darker than normal (non-textured drawing will erroneously sample the texture). Texturing should be disabled (glDisable) or the texture unbound (glBindTexture(GLES20.GL_TEXTURE_2D, 0)) when drawing non-textured faces to avoid this issue.

**Comment by andresoviedo** [comment]
Hello @deakjahn 
Please. Do you have a model to share so we can check what's the issue ?
regards

**Comment by deakjahn** [comment]
You don't need a specific model, just use anything that has some faces with a texture and other faces without, just with a color. The whole model will be rendered with textures enabled because you don't separate faces with and without.

But in the meantime I went forward and modified the source heavily to suit my needs, including supporting more than one object (and removing other formats than .obj and many parts of the functionality I don't need). The whole structure has been changed a lot, so I don't think sending the source back would really help but I'll compile a list of how I solved the multi-object scenario

**Comment by deakjahn** [comment]
First, I no longer use IntBuffers and FloatBuffers when reading the model. Just simple Java lists. They will be copied to buffer in `generateArrays()` when the time comes but there is no need to use them up front. This means that you don't need to read the model twice because we don't need the final count.

Read the model only once. For every new object, create one. The object will have its own vertex, normals and texCoords lists, not a common one for the whole model. Keep a running count of all three and pass them to the object constructor so that it knows which vertex, normal or texCoord it starts with.

After having read the model, iterate over the objects and call their `generateArrays()` and `loadTexture()`. The first will copy the collected lists to the final array buffers. It's here where we can account for the different start indices of the objects. Instead of simply using the index, we subtract the start index:

      int index = vertexIndexes.get(i);
      Triplet value = vertices.get(index - vertsStart);
      vertexArrayBuffer.put(value.toFloats());

That way, we can convert the items the "f" lines refer to to the items in the objects own list.

**Comment by deakjahn** [comment]
Having said that, I'm more than willing to send the source back if you tell me where to, just don't expect it to be a drop-in replacement. :-) I modified quite a lot, removed all functionality I don't need, reshuffled the code, deleted some classes and combined with others, and, in general, removed much of the Java field getters-setters wherever unnecessary (I don't accept the common wisdom of always using them in Java, I let tightly coupled classes that only need to interoperate among themselves and don't need to show an interface to the outside world see each other's fields). Oh, and yes, I never even touched the iOS code, just Android.

**Comment by andresoviedo** [comment]
Hello @deakjahn 
Totally agree with you
Please let me know you that I am continuously improving the app 

About the issues
* Very kind of yours to have a fix for the this ticket  :)
* Wavefront loader is legacy code I inherited. Agree it needs to be improved.

1 of the goals of this project is to have a **core** engine that other people can reuse.
I am :100:  sure there is ways to decouple app components to fit all needs.
Actually, I am right almost releasing a new version that fixes a lot tech debt in app design along with other corrections  I will keep you posted in case you think it's worth it to revisit the code.

Thanks a lot for your feedback

**Comment by deakjahn** [comment]
What if I reply directly to the notification I received from Github? One one hand, it says I can reply directly, on the other hand it has a @noreply.github.com e-mail address.

I would send you the current code, it works just fine for my needs (I will comment on the modifications I made to make it clear).

**Comment by andresoviedo** [comment]
Hi,
Latest version fixes most of the issues you described here like textures mixed up, groups, buffers, etc
Please give it a try
regards
