### ISSUE TITLE
加载一些模型的时候, 贴片没加载出来

### ISSUE THREAD

**Issue by bruce-wmm** [andresoviedo/android-3D-model-viewer#136]

**Comment by bruce-wmm** [comment]
具体就是深颜色的材质, 渲染出来全部是黑色的模型, 材质完全变了

**Comment by andresoviedo** [comment]
你好可以分享模型，让我看看吗？
问候

**Comment by bruce-wmm** [comment]
[陶罐2.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/4473893/2.zip)

**Comment by bruce-wmm** [comment]
应该是解析mtl文件的时候, 有点问题,

**Comment by bruce-wmm** [comment]
能解决吗

**Comment by andresoviedo** [comment]
你好。抱歉耽搁了。
我正在制作主要版本。
我现在正在解决所有问题。
我会及时向大家发布。
问候

**Comment by andresoviedo** [comment]
你好。我可以加载最新版本的模型。请试一试。如果仍有问题，请重新打开票。问候
