### ISSUE TITLE
Add support for Object Name (o) and Group Name (g)

### ISSUE THREAD

**Issue by sw-tt-niravbhavsar** [andresoviedo/android-3D-model-viewer#2]
Hi,

Your demo is really helpful and it loads my .obj file successfully.

Now i want to read Group Name(g) and Object Group (o).

Will you please help to parse it!!

Thanks.

**Comment by andresoviedo** [comment]
Hi,

Sorry for the late answer.

You can start by looking at the class WavefrontLoader.java to see how the
.obj is actually parsed.

https://github.com/andresoviedo/android-3D-model-viewer/blob/master/src/org/andresoviedo/app/model3D/services/WavefrontLoader.java

Can I ask what do you want to do with that group info?

Kind regards

**Comment by niravbsoftweb** [comment]
Thanks for reply.

I want to get info of touching area.

i.e. I have 3D model of building and its obj file. I can load that model using this library. So appreciate for that. Now i want to get room info by touching on that specific rooms in that 3D model.

Help will be appreciated!!

Thanks.

**Comment by ritup22** [comment]
Hi I am having issue with loading other .obj & .mtl file, actully its not being loaded correctly.
Even in app ToyPlane.obj you can check online here http://3dviewer.net/
can you please help me with this?

**Comment by andresoviedo** [comment]
Hey body.  Sorry for the late answer again.
Supporting the object and group name would be awesome to have.
i think is not a big issue to implement it
it could be very handy for apps
i am putting this task into the backlog
kind regards

**Comment by andresoviedo** [comment]
object group and names supported in latest version.
please give it a try
regards
