### ISSUE TITLE
Multiple texture images from MTL file not reflecting in 3D Modal

### ISSUE THREAD

**Issue by VinodVPAndroid** [andresoviedo/android-3D-model-viewer#23]
First of all I want to thank you for your wonderful work. This project help me to learn a lots of thing related Wavefront/STL Parsing and OpenGL rendering in Android application. 

By using the source code , I can able to parse Wavefront and STL files successfully and able to create the 3D model. 

Here I have a question under Rendering Texture on 3D model part, I tried to render the texture on top of 3D model, it failed due to multiple texture images present in the MTL file.

MTL file,

- Contain one texture image, rendering texture is success. 
- Contain more than one texture image, rendering went failed. First texture image is rendered on top of 3D Modal object.

Please give some input to solve this issue.

**Comment by andresoviedo** [comment]
There is already an open ticket for treating this issue. Please subscribe to https://github.com/andresoviedo/android-3D-model-viewer/issues/3 to get news about it
