### ISSUE TITLE
zoom limit

### ISSUE THREAD

**Issue by sunfangcheng** [andresoviedo/android-3D-model-viewer#25]
hellow，how can make the model  set the limits of the zoom   maximum and minimum

**Comment by panshen** [comment]
Hi,I have implement this check out this file https://github.com/panshen/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/controller/TouchController.java

**Comment by andresoviedo** [comment]
There is already an implementation of the zoom limits.  
Zoom out is fixed to 20 units implemented as a bounding box in the camera
Zoom in limited to the center of the object or the world, that is the coordinates 0,0,0
If you want to adjust the zoom in limit, you just have to put a bounding box in the center 0,0,0 and test the camera collision with it.
