### ISSUE TITLE
Unable to use one finger functionality or zoom feature on API 24 & 25

### ISSUE THREAD

**Issue by Marunizer** [andresoviedo/android-3D-model-viewer#26]
It seems that every time I run the application on a VM or actual phone with API 24 or 25(Android 7 & 7.1)
Only the cube object files work as intended. The rest of the obj models (including imported ones) lost functionality with one finger touch functionality as well as zoom functionality. 

When I attempt to touch the screen, this appears in the log : 
10-05 00:57:11.961 25910-25910/org.andresoviedo.dddmodel2 D/Camera: Inside bounds of 'ToyPlane.obj'

Which I found the probable case scenario to be in line 201 of Camera.java
"  Log.d("Camera", "Inside bounds of '" + objects.get(i).getId() + "'");  "
Inside the isOutOfBounds() function.

I am unsure if this is enough to try to identify the problem, but I think it's at least a start, haha.
Please help ! (:

PS: This is an awesome app

**Comment by andresoviedo** [comment]
Hey. Do you still have this issue with the latest apk?

**Comment by andresoviedo** [comment]
No news. Reopen if you still have issues with the zoom
