### ISSUE TITLE
Why animated 3d objects contains .dae format? 

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [andresoviedo/android-3D-model-viewer#33]
i have analysing android-3d-model-viewer.i had confusion about why animated objects contains .dae format only?

**Comment by andresoviedo** [comment]
obj and stl file formats are simple and contains only polygon mesh information. That is, vertices and the faces forming the 3d object. DAE is an XML file format that can contains, besides polygon mesh information, the object skeleton and frame animation data.
