### ISSUE TITLE
Bug in demo option: App crashes

### ISSUE THREAD

**Issue by sachincool** [andresoviedo/android-3D-model-viewer#34]
#### Expected behavior
After launching the app which am not really used to, I needed a tutorial for it's usage but I luckily found a demo of how to design the model. But unfortunately none of the demos was able to play. 

#### Actual behavior
The app keeps crashing everytime I click on a demo to play for how to use it. 

#### How to reproduce
Open the android 3D model viewer app if already installed or download from Google Play Store if not, after launching it go-to demo and after it loads, click any of the demo you wish to view, immediately the app crashes. 

* Browser: infinix note 4 
* Operating system:  android 7

#### Recording Of The Bug
Here is a video to record the bug. 
https://youtu.be/ycGrLlv1Vlg

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/bug-found-in-pla%22%3EUtopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by spapapan** [comment]
I have the same problem, app crashes when loading specific 3d demo objects. Also there is no Exception error printed in the console.

**Comment by andresoviedo** [comment]
It should be fixed in latest version. If it doesn't, please reopen issue.
