### ISSUE TITLE
dae ( Collada) animated files not working

### ISSUE THREAD

**Issue by darwinfrancis** [andresoviedo/android-3D-model-viewer#38]
I have tried many animated dae files but none of them animating except the one provided with sample project stormtrooper.dae.

[Industrial_Fan_2.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/1677435/Industrial_Fan_2.zip)

here i am attaching the files i have tried, kindly please guide me to show animated files.

**Comment by andresoviedo** [comment]
Fully working in latest version 3.0
Please give it a try
if you still have issues please reopen ticket
regards
