### ISSUE TITLE
Crash loading files from disk from kitkat and up

### ISSUE THREAD

**Issue by andresoviedo** [andresoviedo/android-3D-model-viewer#4]

**Comment by Roshaanf** [comment]
Hey buddy , great job thanks for your priceless help , however app is crashing for some models but for others it is working (y)

**Comment by andresoviedo** [comment]
Hey dude.  Thank you for your feedback. 
Believe it or not, all my models are working fine for me :)
Would you mind to provide me an  example of 1 file crashing for you in ticket #5?
Kind regards
