### ISSUE TITLE
Rotate 3d model in its own Y axis

### ISSUE THREAD

**Issue by darwinfrancis** [andresoviedo/android-3D-model-viewer#40]
I would like to rotate a obj model in its own Y axis in 360 degree.
I tried  camera.translateCamera(0.00010f, 0f); but rotation is not smooth.

how do a smooth animation by rotating the obj model.

**Comment by andresoviedo** [comment]
Try this:

Manual animation:

     // onDrawFrame:
     camera.translateCamera(0.005f, 0f);

Automatic animation:

     // one time:
     camera.translateCamera(0.01f, 0f);
     // onDrawFrame
     camera.animate();
