### ISSUE TITLE
How change Light color

### ISSUE THREAD

**Issue by darwinfrancis** [andresoviedo/android-3D-model-viewer#41]
I want to change the default white color of light object a different one, how can i change the color.
I tried setting color to lightPoint  object but it doesn't change the color.

 private static float[] LIGHT_COLOR = {1.0f, 0.0f, 0, 0.0f,};

private final Object3DData lightPoint = Object3DBuilder.buildPoint(lightPosition).setColor(LIGHT_COLOR).setId("light");

Thanks in Advance.

**Comment by andresoviedo** [comment]
LIGHT_COLOR [3] (alpha) is wrong.

Alpha should be > 0.  For example: 1.0f
