### ISSUE TITLE
How to load multiple textures with dae file format for animation?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [andresoviedo/android-3D-model-viewer#46]
Hai iam analysing android-3d-model-viewer app collada loader classes in the app only load single texture with dae. if i load dae file with two or three textures the error came as "There was a problem loading model index=960,length=960".how can i load dae model with multiple textures?

**Comment by andresoviedo** [comment]
the app currently supports only 1 texture.  i set this ticket to "enhancement"

**Comment by ArigarasuthanRepo** [comment]
Ok Thank you.

**Comment by sunfangcheng** [comment]
When will the ability to post more textures publish？

**Comment by andresoviedo** [comment]
Latest version has been tested successfully rending dae models having multiple meshes.
Every mesh may contain 1 texture

Closing this ticket as current version support multiple textures
