### ISSUE TITLE
Sliding experience is not friendly.

### ISSUE THREAD

**Issue by sdaduanbilei** [andresoviedo/android-3D-model-viewer#47]
Now sliding gesture experience is not very friendly, I compared the IOS side gestures, sliding gestures lack precision, now I want to slide back to initialize it is difficult to operate, can optimize the sliding interaction gestures

**Comment by sdaduanbilei** [comment]
I recorded two video comparisons.  [JD](https://drive.google.com/open?id=1Nr484B7IDF5-8ZwmnlzJbqaeKeQ5y8h2)  and   [3D-model](https://drive.google.com/open?id=1RzEXueKNcYORw7-DrHmTp_FEOHLxRFwS)

**Comment by andresoviedo** [comment]
I see.  Rotation should snap to axes using some threshold.

Thanks for the feedback and videos.
