### ISSUE TITLE
how to select the Object3DData in the scene?

### ISSUE THREAD

**Issue by scolar** [andresoviedo/android-3D-model-viewer#48]
public void processTouch(float x, float y) {
		Object3DData objectToSelect = CollisionDetection.getBoxIntersection(getObjects(), parent.getgLView().getModelRenderer(), x, y);
		if (objectToSelect != null) {
			if (getSelectedObject() == objectToSelect) {
				Log.i("SceneLoader", "Unselected object " + objectToSelect.getId());
				setSelectedObject(null);
			} else {
				Log.i("SceneLoader", "Selected object " + objectToSelect.getId());
				setSelectedObject(objectToSelect);
			}
			float[] point = CollisionDetection.getTriangleIntersection2(getObjects(), parent.getgLView().getModelRenderer(), x, y);
			if (point != null) {
				addObject(Object3DBuilder.buildPoint(point).setColor(new float[]{1.0f,0f,0f,1f}));
			}
		}
	}

why the objectToSelect is always null?

**Comment by andresoviedo** [comment]
It shouldn't. objetToSelect is null only when touch (x,y) doesn't intersect any object.

What android / device are you using?

**Comment by andresoviedo** [comment]
Hey. Do you still have the issue?

**Comment by rikapsu2018** [comment]
@andresoviedo I have the same issue
