### ISSUE TITLE
Crash loading BIG models

### ISSUE THREAD

**Issue by andresoviedo** [andresoviedo/android-3D-model-viewer#5]

**Comment by andresoviedo** [comment]
![screenshot_20170210-235309](https://cloud.githubusercontent.com/assets/1988725/22847265/310901b4-efec-11e6-8d6a-366baa22c3be.png)

**Comment by Roshaanf** [comment]
Hey,
this is the file https://drive.google.com/open?id=0B8EpJ4f6DuI_Zk5MZDB1WjZmVjQ
and for some files it is taking a lifetime to render , otherwise application is working correctly.

**Comment by Roshaanf** [comment]
and this https://drive.google.com/open?id=0B8EpJ4f6DuI_T0RTR3d3bF9yRkU file is not loading even when i compiled it with the app.

**Comment by Roshaanf** [comment]
Hey Oviedo , any update about the problem?

**Comment by andresoviedo** [comment]
Hey.

As I told you, I don't have free much time

And I have to take care of my son.

Probably next weekend I can take a look.

I will keep you posted.

Best regards

**Comment by Roshaanf** [comment]
Hey .
 sorry i forgot , yeah take  your time , I can wait :)
regards

**Comment by Roshaanf** [comment]
Hey Oviedo,
How are you?  Have you figuered out the solution yet?
Regards.

**Comment by andresoviedo** [comment]
Hey. I am sorry. My laptop doesn't start. I am waiting to buy a new one :)
Regards

**Comment by andresoviedo** [comment]
Hey. I got a new laptop! :) 

so I opened your hulk file. no problem at all in my alkatel android 6
the second file is a 75MB file.  I had a problem after waiting a lot. 

so. it sound to me like a memory problem.
may I ask what's inside the second model? 

regards

**Comment by Roshaanf** [comment]
hey , 
congrats  , yes size issue thats what i also diagnosed but i guess threads doesnot work with openGl otherwise it would be bit easier , second model is a 3d scanned model of one of my colleague , however it is working on other online .obj viewer
kind regards

**Comment by andresoviedo** [comment]
Hi @Roshaanf.  I could load your "complete" model after fixing the issue. Its taking 180MB of memory.
Kind regards

**Comment by gytai** [comment]
Hi @andresoviedo. I load a model that size is 500M and crashed
