### ISSUE TITLE
java.lang.RuntimeException: Error creating program.

### ISSUE THREAD

**Issue by sriramnatrajan** [andresoviedo/android-3D-model-viewer#51]
` 06-07 17:22:48.006 4222-5030/org.andresoviedo.dddmodel2 E/GLUtil: Could not compile program:  | const int MAX_JOINTS = 200;
    const int MAX_WEIGHTS = 3;
    uniform mat4 u_MVPMatrix;      
    attribute vec4 a_Position;     
    attribute vec3 in_jointIndices;
    attribute vec3 in_weights;
    uniform mat4 jointTransforms[MAX_JOINTS];
    uniform mat4 u_MVMatrix;
    uniform vec3 u_LightPos;
    attribute vec3 a_Normal;
    uniform vec4 vColor;
    varying vec4 v_Color;
    attribute vec2 a_TexCoordinate;varying vec2 v_TexCoordinate;void main()                    
    {                              
      vec4 totalLocalPos = vec4(0.0);
      vec4 totalNormal = vec4(0.0);
        mat4 jointTransform = jointTransforms[int(in_jointIndices[0])];
        vec4 posePosition = jointTransform * a_Position;
        totalLocalPos += posePosition * in_weights[0];
        jointTransform = jointTransforms[int(in_jointIndices[1])];
        posePosition = jointTransform * a_Position;
        totalLocalPos += posePosition * in_weights[1];
        jointTransform = jointTransforms[int(in_jointIndices[2])];
        posePosition = jointTransform * a_Position;
        totalLocalPos += posePosition * in_weights[2];
      gl_Position = u_MVPMatrix * totalLocalPos;
      gl_PointSize = 2.5;         
       vec3 modelViewVertex = vec3(u_MVMatrix * a_Position);
                 vec3 lightVector = normalize(u_LightPos - modelViewVertex);
           vec3 modelViewNormal = vec3(u_MVMatrix * vec4(a_Normal, 0.0));
        float diffuse = max(dot(modelViewNormal, lightVector), 0.1);
          float distance = length(u_LightPos - modelViewVertex);
                diffuse = diffuse * (1.0 / (1.0 + (0.05 * distance * distance)));
      diffuse = diffuse + 0.5;   v_Color = vColor * diffuse;
       v_Color[3] = vColor[3];  v_TexCoordinate = a_TexCoordinate;}                              
    Error compiling program: 
    L1003: Can't link program, because it does not contain a vertex shader
06-07 17:22:48.016 4222-5030/org.andresoviedo.dddmodel2 E/ModelRenderer: There was a problem rendering the object 'truck.obj':Error creating program.
    java.lang.RuntimeException: Error creating program.
        at org.andresoviedo.app.model3D.util.GLUtil.createAndLinkProgram(GLUtil.java:65)
        at org.andresoviedo.app.model3D.model.Object3DImpl.<init>(Object3DImpl.java:45)
        at org.andresoviedo.app.model3D.model.Object3DV9.<init>(Object3DImpl.java:963)
        at org.andresoviedo.app.model3D.model.Object3DBuilder.getDrawer(Object3DBuilder.java:430)
        at org.andresoviedo.app.model3D.view.ModelRenderer.onDrawFrame(ModelRenderer.java:176)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`
Help! Getting error while loading texture.
Thanks in Advance

**Comment by andresoviedo** [comment]
Please try latest version.  It should be fixed.  If not, reopen issue.
