### ISSUE TITLE
Loading .Obj file only (not .mtl file) when color information is given in obj file  

### ISSUE THREAD

**Issue by vivek12345678910** [andresoviedo/android-3D-model-viewer#52]
Is there a way to load a obj file with texture. Like color is given in v x y x cx cy cz formate

**Comment by andresoviedo** [comment]
How is it supposed to be declared the color in .obj file?

This are the specs: 
* http://www.martinreddy.net/gfx/3d/OBJ.spec
* http://www.fileformat.info/format/material/

**Comment by andresoviedo** [comment]
No news.  Reopen this ticket if needed.

**Comment by vivek12345678910** [comment]
Hi, It's resolved
Thanks

**Comment by oc-fmartinez** [comment]
@vivek12345678910 Hi,  How to resolved? 

I need put color to custom object

**Comment by andresoviedo** [comment]
Hello @vivek12345678910 
Did you read my last comment?
There is no way to specify color in obj.
You have to use material file.
Regards
