### ISSUE TITLE
Bounding box error

### ISSUE THREAD

**Issue by Pawcu** [andresoviedo/android-3D-model-viewer#53]
Not sure if this is a bug or I am doing something wrong but when I rotate the model, the bounding box still shows the old location. It scales ok but rotation or positioning updates to the model have no effect:
![image](https://user-images.githubusercontent.com/27457511/41735031-ed9db734-7588-11e8-90e0-6178ddff8985.png)

**Comment by andresoviedo** [comment]
Are you using the latest version of the application?  
Or is a your custom version?

**Comment by Pawcu** [comment]
Hello,
Thanks for getting back to me. This was a while back ago and I have since moved away from using 3d models all together. Having said that if I remember correctly, I was on the latest version on git back then (i was testing this not using the google play application).

**Comment by andresoviedo** [comment]
Ok.  If you work again with 3d and you have any issue we can talk.
Regards
