### ISSUE TITLE
Collada animation with textures fail to render Galaxy S9

### ISSUE THREAD

**Issue by haroldmthyng** [andresoviedo/android-3D-model-viewer#54]
I've been dealing with this issue for over 2 weeks. Collada skeletal animations with textures render blank on the Galaxy S9. Your animation code and all routines render perfectly on all other devices except for the Galaxy S9 running Android 8.0

My suspicion is it's related to rendering issues on the QUALCOMM Adreno GPU chipset. Basically what happens is once the vertex shader manipulates the vertex position non-uniformly, meaning applies different XYZ values per vertex as needed for joint transforms and joint weights, the bound texture renders blank or only periodically on a subset of polygons. Usually it just renders blank, but will result in a sparse flicker for denser geometries.

I've thrown everything at this issue. It's not related to GLES20 vs GLES30. Not a case of incomplete mip-map generation. Not a texture wrap method issue (CLAMP_TO_EDGE vs GL_REPEAT). Not a non-power of 2 texture size issue. It just fails to render correctly on that particular device.

Simply running this project unaltered yields blank results for any of the sample textured Collada files bundled with the project.

There are NO OpenGL errors present. No failures within the logs. Shaders compile fully, but just fail to render.

Here's some data on the device in question.

device finger print:
samsung/starqlteue/starqlteue:8.0.0/R16NW/G960U1UES2ARF4:user/release-keys

at shader initialization:

06-29 09:51:48.552 21498-21543/? I/Adreno: QUALCOMM build                   : bafb8dc, Ic43eb7c732
    Build Date                       : 02/01/18
    OpenGL ES Shader Compiler Version: EV031.22.00.02
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.3.C1.08.00.00.432.017
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING

**Comment by haroldmthyng** [comment]
Surprisingly I stumbled across a resolution for this issue. Seems for that device and GPU there's just a lower MAX_VERTEX_UNIFORM_COMPONENTS. So lowering the `MAX_JOINTS` value fixes this problem. For me, I was able to set the constant value to 100 instead of 200 and it works. (See below)

```
	private final static String vertexShaderCode =
			"const int MAX_JOINTS = 100;\n"
					+ "const int MAX_WEIGHTS = 3;\n"
					+ "uniform mat4 u_MVPMatrix;      \n"

```

I can tell you for the Galaxy S9, seems to error at an array size of 108. Here are a few links I managed to find on the internet regarding this issue. These posts are old, but does highlight the existence of a MAX_VERTEX_UNIFORM_COMPONENTS limit.

https://www.opengl.org/discussion_boards/showthread.php/166170-Max-uniform-matrix-array-size

https://www.gamedev.net/forums/topic/425979-typical-number-of-bones-in-a-model/

https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf

Hopefully, this helps out someone else so they don't lose precious dev time like I did.

**Comment by andresoviedo** [comment]
Glad you found the solution.   Thanks for the feedback

**Comment by haroldmthyng** [comment]
Just happy to contribute any way I can as this library helped me out tremendously with Collada skeletal animation support. :)

**Comment by andresoviedo** [comment]
You are welcome to contribute in any way whenever you want 

If you have any idea it's ok. Otherwise there are many things to be improved, like the collada parser.

Regards
