### ISSUE TITLE
Implement API to change model colors

### ISSUE THREAD

**Issue by ritup22** [andresoviedo/android-3D-model-viewer#6]
Not able to load correct .obj & .mtl
Please check here http://3dviewer.net/ ToyPlane.obj
It shows orange
Can you please help me with this?

**Comment by andresoviedo** [comment]
Hi ritup.  Are you trying to load ToyPlane.obj from external SD card?  If so, please attach the log to see what error you have. KR

**Comment by ritup22** [comment]
No I am not having error
It shows green color in app & in online site it shows orange color

**Comment by andresoviedo** [comment]
Hey. The mtl file is configured with 3 colors: red green and gray.

Please change the colors in mtl, recompile the app and install it.

It the ToyModel changes, then the app is working OK. If you have a
different result, then please submit your updated mtl file and I will check
as soon as I can.

Regards

**Comment by ritup22** [comment]
Thank you.
It worked, I have changed .mtl file
But still I have one doubt.. How will I indetify which Kd color to change
as model will come from api & I will not know  which color it has, at that
time how will I handle?
I have changed last Kd in .mtl file of toyPlane to 1.0,1.0,1.0 & it worked



*Thanks & Regards,**ritu Patel*
Software Developer - Android

*Credencys Solutions Pvt Ltd13th Fl, Landmark, Opp Seema Hall, Anandnagar
Rd, Ahmedabad, GJ 380015*
D: (+91) 26934331 x 303
ritu.patel@credencys.com
www.credencys.com

**Comment by andresoviedo** [comment]
Hey. Not sure to understand your last question.  What API? The different Kd colors are linked to the different parts of the 3d obj file. 

In the ToyModel example you have 3 colors only and a texture.

**Comment by ritup22** [comment]
Ok I meant to say that my obj model with come runtime as per user demand it.
Yes I understand .mtl file structure, my question is that how will I
correct .mtl file format so that every model loads correctly?



*Thanks & Regards,**ritu Patel*
Software Developer - Android

*Credencys Solutions Pvt Ltd13th Fl, Landmark, Opp Seema Hall, Anandnagar
Rd, Ahmedabad, GJ 380015*
D: (+91) 26934331 x 303
ritu.patel@credencys.com
www.credencys.com

**Comment by andresoviedo** [comment]
hi @ritup22  not sure to understand. are you trying to change the colors of the loaded model in your app?
regards

**Comment by ritup22** [comment]
Yes color in .mtl file



*Thanks & Regards,**ritu Patel*
Software Developer - Android

*Credencys Solutions Pvt Ltd13th Fl, Landmark, Opp Seema Hall, Anandnagar
Rd, Ahmedabad, GJ 380015*
D: (+91) 26934331 x 303
ritu.patel@credencys.com
www.credencys.com

**Comment by andresoviedo** [comment]
Hey.  The change colors feature is not implemented.
If you want to do it yourself, you would have to post process the materials in [Object3DData.java](https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/model/Object3DData.java#L60)
Here is were the colors are generated for 3D [Object3DBuilder.java#L515](https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/model/Object3DBuilder.java#L515)
I am chaning the title of this issue to "Implement API to change model colors"

**Comment by biswanathsahoo** [comment]
Hi,
 I am also getting the same issue. When I am loading a model, it's color is changing. The original color of the model is white but when I am loading the model its color is changing to green.

**Comment by sk8darr** [comment]
Hi @andresoviedo,

I am also trying to implement this feature. I founded where can we change the material (in my case) attached to the obj but this is not showing, i guess need to refresh the scene or something... 

How can i re-build or re-read the object to showing the changes?

Regards

**Comment by andresoviedo** [comment]
Hi,   Replace the setColor function in Object3DData.java like this:


    public Object3DData setColor(float[] color) {
	    // color variable when using single color
		this.color = color;
		
		// color buffer when using multiple colors
		if (this.vertexColorsArrayBuffer != null && this.vertexColorsArrayBuffer.capacity() > 0){
			for (int i=0; i<vertexColorsArrayBuffer.capacity(); i+=4){
				vertexColorsArrayBuffer.put(i,color[0]);
                                vertexColorsArrayBuffer.put(i+1,color[1]);
                                vertexColorsArrayBuffer.put(i+2,color[2]);
                                vertexColorsArrayBuffer.put(i+3,color[3]);
			}
		}
		return this;
	}



Then call  

`obj.setColor(new float[] { 1f, 0f, 1f, 1f });`

**Comment by andresoviedo** [comment]
Hi. If you want to paint yourself the model programmatically, you would have to parse the *groups* of the model and save it on the Object3DData. Then you will be able to paint them independently, with material or any color.

So, in order to save the groups for later processing, you need at least a structure like this:

    IdGroup : gasoline_tank
    vertexList:1,2,30,41,1000,etc
    
    IdGroup:. wheels
    vertexList:. 23,24,80,2000,etc


With that structure you can populate arrayVertexColorBuffer object.

**Comment by sk8darr** [comment]
> Hi. If you want to paint yourself the model programmatically, you would have to parse the _groups_ of the model and save it on the Object3DData. Then you will be able to paint them independently, with material or any color.
> 
> So, in order to save the groups for later processing, you need at least a structure like this:
> 
> ```
> IdGroup : gasoline_tank
> vertexList:1,2,30,41,1000,etc
> 
> IdGroup:. wheels
> vertexList:. 23,24,80,2000,etc
> ```
> With that structure you can populate arrayVertexColorBuffer object.

Hi. Ok, so that means i need to modify the WavefrontLoader class in the readModel method for parse the group over 'o'  rigth?

**Comment by andresoviedo** [comment]
@sk8dar yes.  You would need to:
- extend Object3DData with a Map<String,IntBuffer>
- improve Wavefrontloader to parse groups.

Regards

**Comment by andresoviedo** [comment]
API has the method `Oject3DData.setColor(float[])`  available.

**Comment by xiaoxing1992** [comment]
> > Hi. If you want to paint yourself the model programmatically, you would have to parse the _groups_ of the model and save it on the Object3DData. Then you will be able to paint them independently, with material or any color.
> > So, in order to save the groups for later processing, you need at least a structure like this:
> > ```
> > IdGroup : gasoline_tank
> > vertexList:1,2,30,41,1000,etc
> > 
> > IdGroup:. wheels
> > vertexList:. 23,24,80,2000,etc
> > ```
> > 
> > 
> > With that structure you can populate arrayVertexColorBuffer object.
> 
> Hi. Ok, so that means i need to modify the WavefrontLoader class in the readModel method for parse the group over 'o' rigth?

Hello you this group of different color inside implements, please can you help me, I need your demo
