### ISSUE TITLE
Limit zoom

### ISSUE THREAD

**Issue by cancanw** [andresoviedo/android-3D-model-viewer#68]
When the model is enlarged to a certain extent, it becomes blank. Why not limit its maximum scale?

**Comment by andresoviedo** [comment]
#43

**Comment by pt429sy** [comment]
Hello, I can try to help with this issue

**Comment by andresoviedo** [comment]
Hello @pt429sy 

Thank you. I was thinking to put a bounding box in the middle of the object. I tested it and it works.
I was just going to push it.

Do you have a better idea ?

Regards

**Comment by andresoviedo** [comment]
Bounding box in the near and far plane to limit zoom

**Comment by amit-iottive** [comment]
@andresoviedo Can you share the code to limit zoom?
