### ISSUE TITLE
Dae files not loaded

### ISSUE THREAD

**Issue by malizadehq** [andresoviedo/android-3D-model-viewer#69]
Dae file (only with animation) created by blender not working. Do you have any idea?

I import/export cowboy.dae without any change, did not show again!

**Comment by malizadehq** [comment]
check this sample
[test.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/2475561/test.zip)

**Comment by andresoviedo** [comment]
Thanks. I will take a look to your model.

**Comment by andresoviedo** [comment]
Fixed in latest version. Please try.
Regards
