### ISSUE TITLE
chartlet of DAE model

### ISSUE THREAD

**Issue by cancanw** [andresoviedo/android-3D-model-viewer#72]
The color of the DAE model will be darker than the actual picture. What will be the reason?
thanks in advance.

**Comment by cancanw** [comment]
diffuse = diffuse + 1.0;这个数据由0.5改为1.0就好了

**Comment by cancanw** [comment]
2.0.2版本

**Comment by cancanw** [comment]
but 2.2.0

**Comment by andresoviedo** [comment]
Please try latest version.
You can disable light influence however.
