### ISSUE TITLE
How to use vertex color with .obj file

### ISSUE THREAD

**Issue by mondec2112** [andresoviedo/android-3D-model-viewer#73]
Hi, I'm trying to load an .obj model with the vertex colors in it.

The lines of vectors in the .obj file are something like this:
vn -2.755000 -2.994675 -4.785977
v -0.224703 -0.687804 2.470051 **0.572549 0.082353 0.043137**
vn -2.598509 -3.086801 -4.814801
v -0.223505 -0.688861 2.470051 **0.572549 0.082353 0.047059**

The last 3 numbers of "v" line is the RGB color of each vertex. After loading the object, it is just a white color thing without any color. How can I read the RGB vertex color with this app? 
Thanks.

**Comment by andresoviedo** [comment]
Hi @mondec2112 

* The color goes in the material.mtl file (Kd)
* The obj file references the mtl file (mtllib)
* The obj file contains "usemtl" directive before vertex to associate them a specific color

Here you have an example.  If you have any doubt don't hesitate and ask.

https://github.com/andresoviedo/android-3D-model-viewer/blob/master/models/cube.obj
https://github.com/andresoviedo/android-3D-model-viewer/blob/master/models/cube.mtl

**Comment by mondec2112** [comment]
Hi @andresoviedo 
Thanks for replying but I'm using vertex color included in its .obj file, not using .mtl along with it. Can you help me with this? Thanks.

**Comment by andresoviedo** [comment]
Hi @mondec2112 

I didn't know the color could be specified along with the vertex definition. lol

In the [spec](http://www.martinreddy.net/gfx/3d/OBJ.spec) I only see 'v x y z [w]'.

Could you please tell which tool works with this type of vertex?
