### ISSUE TITLE
.PLY file format support

### ISSUE THREAD

**Issue by shaji-Dev** [andresoviedo/android-3D-model-viewer#75]
Hi,

Thank you for this app. 

Will it be able to support .ply file formats with colors?

**Comment by andresoviedo** [comment]
Hi.  The purpose of the app is not to support all available formats. 

However, if there are more users wanting support for this format or any other format it may have sense to implement it in the app.

Let's see if anyone votes this request or want to implement it.

Regards

**Comment by shaji-Dev** [comment]
Thank you for the quick response. 

I've been trying to load .obj files, the shape loads just fine but it's not loading the colors as well, in other 3D viewer apps it does. Is there an option to turn the colors on and off or something?

**Comment by andresoviedo** [comment]
The app supports obj colors in material file.
If your obj file contains color info, please say which tool are you using to generate those files and provide 1 example if possible.

**Comment by shaji-Dev** [comment]
![emb3d](https://user-images.githubusercontent.com/10184170/47992697-d4641580-e0ed-11e8-9cc0-f270b76ff5df.jpg)
![3d model viewer](https://user-images.githubusercontent.com/10184170/47992698-d4641580-e0ed-11e8-8a4e-53b57540cefc.jpg)

It should show in green as the first file but as you can see in the second screenshot in 3D Model Viewer it's blank.

Here are some files to test, the one I'm using in the example is b2.obj: 
[test.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/2547976/test.zip)


Thank you.

**Comment by shaji-Dev** [comment]
I used Meshlab to generate the files.

**Comment by sk8darr** [comment]
Hi, is there any way to make this possible? or a way for change objects color programmatically?

**Comment by andresoviedo** [comment]
Hello @shaji-Dev  
sorry for the delay.   the zip you provided does not contain any *.mtl file (material)
Kind regards

**Comment by andresoviedo** [comment]
Hello @sk8darr 
Yes. you can change color by invoking obj.setColor( float[] ) 
Kind regards
