### ISSUE TITLE
Hello, may I ask if the camera rotating around the model provides method removal

### ISSUE THREAD

**Issue by 619647373** [andresoviedo/android-3D-model-viewer#79]
Hello, may I ask if the camera rotating around the model provides method removal

**Comment by andresoviedo** [comment]
Hey.  I suppose you mean the light rotating around the model.

You have to comment the following line:

https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/view/ModelRenderer.java#L170
