### ISSUE TITLE
How do I rotate along the y axis

### ISSUE THREAD

**Issue by 619647373** [andresoviedo/android-3D-model-viewer#82]
Now what happens is that I set the Y-axis to 0, and the pattern is that I rotate 360 degrees around an invisible cylinder.What I need is to rotate along the Y-axis, may I ask where to deal with it? Thank you very much for your help, thank you

**Comment by andresoviedo** [comment]
Hey. If you want to rotate along the y axis you have to call Object3DData.setRotationY(float)

**Comment by 619647373** [comment]
Thank you, I have found your way to use the function.Wishing you a lifetime of peace 


------------------ 原始邮件 ------------------
发件人: "Andres Oviedo"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 凌晨2:53
收件人: "andresoviedo/android-3D-model-viewer"<android-3D-model-viewer@noreply.github.com>;
抄送: "Liu"<619647373@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [andresoviedo/android-3D-model-viewer] How do I rotate along they axis (#82)




Hey. If you want to rotate along the y axis you have to call Object3DData.setRotationY(float)

**Comment by arunavsikdershuvo** [comment]
@619647373 Hi, I'm actually stuck at moving the camera along with x-axis. Can you give me some idea or code snippet how did you implement rotation along y-axis? It would help me a lot. Thanks in advance.

**Comment by SkyEric** [comment]
> @619647373 Hi, I'm actually stuck at moving the camera along with x-axis. Can you give me some idea or code snippet how did you implement rotation along y-axis? It would help me a lot. Thanks in advance.

@arunavsikdershuvo 
Did you solve the problem? I have this problem too。thanks

**Comment by arunavsikdershuvo** [comment]
> > @619647373 Hi, I'm actually stuck at moving the camera along with x-axis. Can you give me some idea or code snippet how did you implement rotation along y-axis? It would help me a lot. Thanks in advance.
> 
> @arunavsikdershuvo Did you solve the problem? I have this problem too。thanks

@SkyEric No. I couldn't implement an optimised solution, so I stopped using this library. Sorry that I couldn't be of no help.

**Comment by SkyEric** [comment]
> > > @619647373 Hi, I'm actually stuck at moving the camera along with x-axis. Can you give me some idea or code snippet how did you implement rotation along y-axis? It would help me a lot. Thanks in advance.
> > 
> > 
> > @arunavsikdershuvo Did you solve the problem? I have this problem too。thanks
> 
> @SkyEric No. I couldn't implement an optimised solution, so I stopped using this library. Sorry that I couldn't be of no help.

@andresoviedo 
Can I ask again how you solved it in the end? Or which library are you using?

**Comment by arunavsikdershuvo** [comment]
> > > > @619647373 Hi, I'm actually stuck at moving the camera along with x-axis. Can you give me some idea or code snippet how did you implement rotation along y-axis? It would help me a lot. Thanks in advance.
> > > 
> > > 
> > > @arunavsikdershuvo Did you solve the problem? I have this problem too。thanks
> > 
> > 
> > @SkyEric No. I couldn't implement an optimised solution, so I stopped using this library. Sorry that I couldn't be of no help.
> 
> @andresoviedo Can I ask again how you solved it in the end? Or which library are you using?

@andresoviedo My requirements could not be developed using Android 3D native libraries available. So I moved to web, and developed using vue js and show the 3D content into webview for Android mobile application.
