### ISSUE TITLE
How to translate camera on y axis ?

### ISSUE THREAD

**Issue by jehadmashhour** [andresoviedo/android-3D-model-viewer#83]
Hello , thanks for this great library . 

Plz ,  i want to move a 3d model on Y axis only , at the same time i want also move the camera parallel with the 3d model as i mentioned on Y axis . 

I got the way to translate the 3d model on Y axis but i still struggle with translating the camera on Y axis  ? 

Any hint  , plz

**Comment by andresoviedo** [comment]
Hi. The Camera class has a method Camera#translate(dX,dY) 

If you want to rotate the camera around y axis, just call Camera#translate() method with dY=0 and dX=x. That means there is no movement vector up or down but "x" to the right or left.

**Comment by jehadmashhour** [comment]
@andresoviedo 

I think you misunderstood me , I don't need to rotate the camera , i want to move it (**translating**) from it's position to above on Y axis only?  I have used **Camera#translate()  method** but it's only for rotation ??

I was working on a way to move the a 3d object with the camera on y axis to be **a parallel movement** .

**but i still struggle with translating the camera on Y axis ?**

So i found another solution to do that but i see an unexpected result , i use : 

**Matrix.translateM(modelProjectionMatrix, 0, 0, 3, 0);**  // to move 3 units on y axis .

but the final view result is not right !! , Why plz ?? 

![screenshot_2018-12-09-19-36-29](https://user-images.githubusercontent.com/14905922/49700680-b86efa80-fbea-11e8-84cf-a2dc8d56d7a3.png)


This is the final result after moving :

![screenshot_2018-12-09-19-36-59](https://user-images.githubusercontent.com/14905922/49700688-d76d8c80-fbea-11e8-8e80-3be9b2fe2076.png)


Plz Plz help me ? As you see in the final result the 3d object **doesn't showing from the center , i see it from the bottom** , Why ??

**Comment by andresoviedo** [comment]
Hi. Keep in mind that there is 3 vectors in the camera: 
    
    position (xPos,yPos,zPos)
    look (xLook,yLook,zLook)
    up (xUp,yUp,zUp)

If you see the model from the bottom its because you are looking at wrong direction.

So. Try translating the look vector as well.

Regards

**Comment by jehadmashhour** [comment]
@andresoviedo Thanks for ur replay. 

I have tried to change the look , position & up on Y axis but i still struggle with it , so please can u help me ? <_> , i only need to move my 3d model only on Y axis as i have sent in the images above  , but i see the bottom of 3d model ?! Maybe i can say i need something similar to orthographic camera view  .

I tried theses ways but no avail : 
1 - StrafeCam : by sending dx = 0 , dy = 5f   ; but this makes my 3d model goes deeply on Z axis . 

2 - TranslateCamera : It makes my 3d model rotates about itself . 

3 - Rotate(float rotViewerZ) : It makes my 3d model rotates about itself  , maybe it rotates on Z axis only. 

4 - Rotate(float incX, float incY) : by sending dx = 0 , dy = 0.4f  , It makes my 3d model goes up on Y axis close to what I want but i see it isn't in the center x axis which means this will effect on the X values & Z values  & i think it related to rotating not moving . 

5-MoveCameraZ(float direction) : It makes only my 3d model moves on Z axis , i think it maybe will work if i can change this code to move my 3d model on Y Axis only  but i couldn't do it , So please can u help me  ?? 

<_> Please i still struggle with that , ur help will be appreciated ?

**Comment by andresoviedo** [comment]
Hi @jehadmashhour   Did you achieve what you wanted?

**Comment by SkyEric** [comment]
> Hi. The Camera class has a method Camera#translate(dX,dY)
> 
> If you want to rotate the camera around y axis, just call Camera#translate() method with dY=0 and dX=x. That means there is no movement vector up or down but "x" to the right or left.


How does it relate to 0 to 180 degrees on the Y-axis? Let's say I want to rotate 30 degrees about the Y-axis, what do I do?

**Comment by andresoviedo** [comment]
Solved in #212
