### ISSUE TITLE
Why Object3DData.setVisible(false) not working ?

### ISSUE THREAD

**Issue by jehadmashhour** [andresoviedo/android-3D-model-viewer#84]
Why Object3DData.setVisible(false) not working ? 

I want to hide a 3d model then show it again .

**Comment by andresoviedo** [comment]
hI @jehadmashhour   Good question.
Not sure why, but [there should be an if-sentence over here](https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/view/ModelRenderer.java#L179)

If you want, you can implement the if-line there:

    if (!objData.isVisible()) continue;

Kind regards

**Comment by jehadmashhour** [comment]
Thank u so much , work like a charm
