### ISSUE TITLE
Making the bounding box invisble

### ISSUE THREAD

**Issue by blauergolfer** [andresoviedo/android-3D-model-viewer#85]
Hello,

I have a question: How can I change the color of the lines of the bounding box. The best case would be if they are invisble.

Thanks in advance for the answer!
Best regards,
Andy

**Comment by andresoviedo** [comment]
Hi @blauergolfer .  You have currently 1 button on user interface to hide bounding box.
Otherwise, check BoundingBoxBuilder which sets the color of the BoundingBox.
Kind regards
