### ISSUE TITLE
how to display a 3D map By Octree format？

### ISSUE THREAD

**Issue by lihongwen1** [andresoviedo/android-3D-model-viewer#87]
I want to use opengl to display a 3d map. The map format is OctoMap - An Efficient Probabilistic 3D Mapping Framework Based on Octrees. I see the Octree class in the engine module. Can it be implemented?

**Comment by andresoviedo** [comment]
Hi @lihongwen1 .  Not sure how OctoMap would fit.  
The Octree on app is part of the Collision Detection system. 
Basically, it maps all the model vertex into an Octree.
