### ISSUE TITLE
3D model viewer changing model color automatically

### ISSUE THREAD

**Issue by NavjeetSaini26** [andresoviedo/android-3D-model-viewer#89]
3D model changing color of model into grey automatically when picking 3D model from storage directory .

**Comment by andresoviedo** [comment]
Hi @NavjeetSaini26   Are you trying to load your own model from external storage?
Please, what's your 3d file format ? 
If it's obj, please check it points to a valid mtl file.

**Comment by andresoviedo** [comment]
Hi. Do you have still the issue?

**Comment by malikmotani** [comment]
Hello @andresoviedo ,
I'm trying the same by loading a .dae file from assets. My file contains a 3d object with a single color. Is there any way we can show multiple colors whole rendering the object?

**Comment by andresoviedo** [comment]
Hello @malikmotani 
not sure to understand you question
would you please elaborate your question please?
regards

**Comment by malikmotani** [comment]
@andresoviedo I have a 3d object in my assets, now I want to change its color programmatically, is it possible using this library?
