### ISSUE TITLE
Models not rendering correctly

### ISSUE THREAD

**Issue by yperess** [andresoviedo/android-3D-model-viewer#92]
I have two models that I've tested, one is an animated model and the other a simple model from Google Poly (https://poly.google.com/view/foCrNyhZh7h). The animated one crashes with an error and the Google poly one doesn't look right (colors are all wrong).
[04c75a02-ba0a-4fb0-89d7-0e8fe4cbd5b4.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/2777221/04c75a02-ba0a-4fb0-89d7-0e8fe4cbd5b4.zip)

**Comment by andresoviedo** [comment]
Thank you @yperess .  I'll take a look asap

**Comment by yperess** [comment]
Thanks, I'll chip in as soon as I have some free cycles at work.
