### ISSUE TITLE
[Ask] How to customize Model Acrivity View?

### ISSUE THREAD

**Issue by Nialixus** [andresoviedo/android-3D-model-viewer#93]
1. Is it possible to inflate the model activity view?
or
2. How to edit the view or can we transform it into xml?

**Comment by andresoviedo** [comment]
Hi,
1- the model activity view is basically the OpenGL renderer. You can add more items to menu or completely redesign screen. It's up to you 
2- there.is already a "activity_model.xml" layout wich you can edit.

Regards

**Comment by Nialixus** [comment]
So that is possible to redesign the screen using xml, but how to connect the activity_model and set it as content view of model activity while it is displaying the gLView?

`// Create a GLSurfaceView instance and set it
        // as the ContentView for this Activity.
        gLView = new ModelSurfaceView(this);
        gLView.setBackgroundDrawable(
                new ColorDrawable(0x66ffffff));
        setContentView(gLView);`

**Comment by Nialixus** [comment]
So that is possible to redesign the screen using xml, but how to connect activity_model and set it as content view while it is displaying the gLView?

`// Create a GLSurfaceView instance and set it
        // as the ContentView for this Activity.


        gLView = new ModelSurfaceView(this);
        gLView.setBackgroundDrawable(
                new ColorDrawable(0x66ffffff));
        setContentView(gLView);`

**Comment by Nialixus** [comment]
So that is possible to redesign the screen using xml, but how to connect activity_model and set it as content view while it is displaying the gLView?

`// Create a GLSurfaceView instance and set it
// as the ContentView for this Activity.

    gLView = new ModelSurfaceView(this);
    gLView.setBackgroundDrawable(
            new ColorDrawable(0x66ffffff));
    setContentView(gLView);`

**Comment by jewelbao** [comment]
@Nialixus  hope the following code is helpful
```
 setContentView(R.layout.activity_content);
 RelativeLayout contentLayout = findViewById(R.id.layout_content);
 ModelSurfaceView gLView = new ModelSurfaceView(this);
 contentLayout .addView(gLView, 0);
```
