### ISSUE TITLE
[Ask] Change model color?

### ISSUE THREAD

**Issue by MarcoCozza** [andresoviedo/android-3D-model-viewer#94]
There's a way to change the color chosen to render the model? Default is gray .
Another question, after I loaded a model in the View there's the action bar (where you can chose to enable/disable texture, light, etc.) which hides after few seconds, there's a way to avoid it?

Sorry for my bad English

**Comment by andresoviedo** [comment]
Hello body
You can change default model color in Object3DData.java . There is a constant.
If you want to disable immersive full screen mode you can do it on MenuActivity.java. there is a parameter when launching the ModelActivity where you can set to false.
Regards

**Comment by andresoviedo** [comment]
Hi.  The immersive mode has been fixed in latest version.
However, a new option to disable immersive mode is now available on the menu.
Regards
