### ISSUE TITLE
OpenCV Integration

### ISSUE THREAD

**Issue by chinmay27** [andresoviedo/android-3D-model-viewer#95]
I am trying to render a 3D object over my hand ( using OpenCV ) in android. 
Can that be done using this engine ?

**Comment by andresoviedo** [comment]
Hello @chinmay27
If you want to draw 3d objects you can do it using the app. 
I think it's possible to draw using OpenCV as well.
However, I suppose either you paint with one or the other.
If you explain a little bit more your use case with OpenCV maybe I can tell you more.
Regards
