### ISSUE TITLE
Is this library supports normal map ?

### ISSUE THREAD

**Issue by jehadmashhour** [andresoviedo/android-3D-model-viewer#96]
It's really awesome library and i still wait the new update of it with a lot of changes on the refactoring code side or on the features , please please do that as soon as possible .

My question :  Is this library supports normal map ?

**Comment by andresoviedo** [comment]
Hi.   The app is a viewer.  It has limited processing capabilities.
If you want to load a "normalized" mesh, I would rather suggest you to do it on your preferred tool, then export it (obj, stl or dae), then load the model with the app.

About the refactoring, there is already a division between the app and the engine.
Is there anything you would like to see refactored?

Regards
