### ISSUE TITLE
Is it possible to make a stereoscopic rendering?

### ISSUE THREAD

**Issue by MarcoCozza** [andresoviedo/android-3D-model-viewer#97]
There is a way to render the model in stereoscopic way? I need this cause I have to visualize the model on a Epson BT-300

**Comment by andresoviedo** [comment]
Hello body
Not sure how Epson BT-300 works
However, there is plans to implement stereoscopic rendering in Android.
Regards

**Comment by andresoviedo** [comment]
Hey. Stereoscopic rendering is available on latest version.
Regards
