### ISSUE TITLE
render obj file to 3d model

### ISSUE THREAD

**Issue by PaikWai** [andresoviedo/android-3D-model-viewer#98]
Hi, i have create an OBJ file in my android apps. Can you show me the way how to render the OBJ File to 3D model?

**Comment by andresoviedo** [comment]
Hi.  I'm not sure to understand your question.
Please, can you explain what you are trying to do?
Regards

**Comment by andresoviedo** [comment]
Hey.  Stereoscopic rendering is available on latest version.
Regards
